## Day7b

In [1]:
import numpy as np

In [2]:
a = np.array([[2 , 2] , 
              [1 , 1]])

In [3]:
b = np.array([[3 , 3], 
              [4 , 4]])

In [4]:
c = np.concatenate((a , b) , axis = 0)
c

array([[2, 2],
       [1, 1],
       [3, 3],
       [4, 4]])

In [5]:
d = np.concatenate((a , b) , axis = 1)
d

array([[2, 2, 3, 3],
       [1, 1, 4, 4]])

In [8]:
#find out the number of dimension of an array
c.ndim

2

In [9]:
d.ndim

2

In [14]:
e = np.array([[[11 , 11],
            [22 , 22],
             [33 , 44]],
             [[55 , 55], 
             [66 , 66]]])

e.ndim

C:\Users\DIGITA~1\AppData\Local\Temp/ipykernel_7276/142746536.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  e = np.array([[[11 , 11],


1

In [24]:
f = np.zeros((4 , 2 , 2))
f

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [25]:
f.ndim

3

In [26]:
f.shape

(4, 2, 2)

In [28]:
g = np.arange(6)
g

array([0, 1, 2, 3, 4, 5])

In [31]:
#reshape your array
h = g.reshape(3 , 2)
h

array([[0, 1],
       [2, 3],
       [4, 5]])

## Day8 Markdown language 